#!/usr/bin/env sh

yabai -m signal --add \
      label=update_state_window_created \
      event=window_created \
      action="~/.config/yabai/scripts/window_created.sh window_created"

yabai -m signal --add \
      label=update_state_application_launched \
      event=application_launched \
      action="~/.config/yabai/scripts/window_created.sh"

yabai -m signal --add \
      label=space_changed \
      event=space_changed \
      action="~/.config/yabai/scripts/signal_uebersicht.sh"

yabai -m signal --add \
      label=display_changed \
      event=display_changed \
      action="~/.config/yabai/scripts/signal_uebersicht.sh"

yabai -m signal --add \
      label=display_added \
      event=display_added \
      action="~/.config/yabai/scripts/displays_changed.sh display_added"

yabai -m signal --add \
      label=display_removed \
      event=display_removed \
      action="~/.config/yabai/scripts/displays_changed.sh"

# Put iTerm on space 1
yabai -m signal --add \
      label=iterm \
      app="^iTerm2$" \
      event=application_launched \
      action="~/.config/yabai/scripts/assign_app.sh 1"

# Put iMessage on space 2
yabai -m signal --add \
      label=messages \
      app="^Messages$" \
      event=application_launched \
      action="~/.config/yabai/scripts/assign_app.sh 2"

# Put slack on space 2
yabai -m signal --add \
      label=slack \
      app="^Slack$" \
      event=application_launched \
      action="~/.config/yabai/scripts/assign_app.sh 2"

# Put Quiver space 3
yabai -m signal --add \
      label=quiver \
      app="^Quiver$" \
      event=application_launched \
      action="~/.config/yabai/scripts/assign_app.sh 3"

# Put Spotify space 4
yabai -m signal --add \
      label=spotify \
      app="^Spotify$" \
      event=application_launched \
      action="~/.config/yabai/scripts/assign_app.sh 4"

# Put Firefox space 5
yabai -m signal --add \
      label=firefox \
      app="^Firefox$" \
      event=application_launched \
      action="~/.config/yabai/scripts/assign_app.sh 5"

